name: Update Service Tags

on:
  schedule:
    - cron:  '0 0 * * 2'
  workflow_dispatch:

permissions:
      id-token: write
      contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Updated Service Tags
      shell: pwsh
      run: |
        Set-Location $ENV:GITHUB_WORKSPACE
        Write-Host "workspace: $ENV:GITHUB_WORKSPACE"
        dir
        ./src/Get-AzureIps.ps1
    - name: Commit Changes
      run: |
        cd $GITHUB_WORKSPACE
        now=$(date)
        git config --global user.email "${{ vars.GIT_CONFIG_USER_EMAIL }}"
        git config --global user.name "${{ vars.GIT_CONFIG_USER_NAME }}"
        git add --all
        if [ -n "$(git status --porcelain)" ]
        then
          git commit -a -m "Update Service Tags $now"
          git push
        fi
